<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1> Try Catch Block !</h1>
    <script>
        var a = 10;
        function checkValue(a){
            try{
                if(a===10){
                    throw 'error , a less than 10'
                }
                return 'try statement returned'; // holds until finally and so do not return this.
            } catch {
                return 'catch statement returned';                
            } finally {
                return ' finally statement returned';
                // If return is present in the finally statement than the others return statement are halted and
                // returns of the finally block. 
                // OVERWRITES THE PREVIIOUS RETURN  
            }
        }
        checkValue(a);


        function f() {
            try {
                throw 'bogus';
            } catch(e) {
                console.log('caught inner "bogus"');
                throw e; // this throw statement is suspended until 
                        // finally block has completed
            } finally {
                return false; // overwrites the previous "throw"
            }
            // "return false" is executed now
        }
        
        try {
            console.log(f());
        } catch(e) {
            // this is never reached! 
            // while f() executes, the `finally` block returns false, 
            // which overwrites the `throw` inside the above `catch`
            console.log('caught outer "bogus"');
        }


        // function doSomethingErrorProne() {
        //     if (ourCodeMakesAMistake()) {
        //         throw (new Error('The message'));
        //     } else {
        //         doSomethingToGetAJavascriptError();
        //     }
        //     }
        //     try {
        //     doSomethingErrorProne();
        //     } catch (e) {               // NOW, we actually use `console.error()`
        //     console.error(e.name);    // logs 'Error'
        //     console.error(e.message); // logs 'The message', or a JavaScript error message
        //     }
    </script>
</body>
</html>